apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-secret
  namespace: external-dns-unifi-webhook
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: unifi-api-token
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: "unifi-api-token"
      property: api-key