apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Azoknak az erőforrásfájloknak a listája, amelyeket a Kustomize feldolgoz
resources:
  - ns.yaml
  - ds-ingress.yaml
  - middleware.yaml

helmCharts:
  - name: traefik                       # A Helm chart neve
    repo: https://traefik.github.io/charts # A chart repository URL-je
    version: 35.3.0                      # A chart verziója
    releaseName: traefik                
    namespace: traefik                   # A névtér, ahova a chart települ
    valuesFile: values.yaml              
    includeCRDs: true  


