apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-szilardshome
  namespace: gateway
spec:
  dnsNames:
    - "*.szilardshome.com"
    - szilardshome.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: szilardshome-wildcard-tls
  usages:
    - digital signature
    - key encipherment