apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - dash-ingress.yaml
  - dash-middleware.yaml
  - dash-secret.yaml
  - default-headers.yaml


helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: v35.4.0
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    includeCRDs: true
