apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - namespace2.yaml
  - cloudflare-external-secret.yaml
  - cluster-issuer.yaml
  - tls-internal-cert.yaml
  - tls-external-cert.yaml


helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesFile: values.yaml