apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-k3s
provisioner: smb.csi.k8s.io
parameters:
  source: //10.10.2.100/media
  csi.storage.k8s.io/node-stage-secret-name: smbcreds
  csi.storage.k8s.io/node-stage-secret-namespace: csi-driver-smb
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - noperm
  - mfsymlinks
  - vers=3.0
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
