apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  - namespace.yaml
  - tls-external-cert.yaml
  - external-clusterrolebinding.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 36.1.0
    releaseName: traefik-external
    namespace: traefik-external
    valuesFile: values.yaml

