apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd-local.szilardshomelab.com`) # change to your domain
      kind: Rule
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd-local.szilardshomelab.com`) # change to your domain
      kind: Rule
      services:
        - name: argocd-server
          port: 80
    - match: Host(`argocd.szilardshomelab.com`) # change to your domain
      kind: Rule
      services:
        - name: argocd-server
          port: 80
      middlewares:
        - name: default-headers