apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Core infrastructure components
  sourceRepos:
    - '*' # In production, specify exact repo URLs
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin role for infrastructure project
      policies:
        - p, proj:infrastructure:admin, applications, *, infrastructure/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-apps
  namespace: argocd
spec:
  description: Project for my custom applications hosted in the my-apps folder
  # Allow deploying apps to any namespace
  destinations:
    - namespace: '*'
      server: '*'
  # Allow deploying namespaced resources from specific groups
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  # Resources that can be created at cluster scope
  clusterResourceWhitelist:
    - group: 'external-secrets.io'
      kind: 'ClusterSecretStore'
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*' # Allow deploying from any Git repository, adjust if needed
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Monitoring and observability components
  sourceRepos:
    - '*' # In production, specify exact repo URLs
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
  # Allow all cluster resources like infrastructure since monitoring needs similar privileges
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Admin role for monitoring project
      policies:
        - p, proj:monitoring:admin, applications, *, monitoring/*, allow
