apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k3s
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        k3s: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets