apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: 1password
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        Kubernetes: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: 1passwordconnect
            key: token
            namespace: external-secrets