k8sServiceHost: "10.10.4.11"
k8sServicePort: "6443"

kubeProxyReplacement: true

l2announcements:
  enabled: true

externalIPs:
  enabled: true

k8sClientRateLimit:
  qps: 50
  burst: 200  

operator:
  replicas: 1  # Uncomment this if you only have one node
  rollOutPods: true

rollOutCiliumPods: true