apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: control-plane-vip-pool
  namespace: kube-system
spec:
  blocks:
    - start: "10.10.4.50"
      stop: "10.10.4.50"
  serviceSelector:
    matchLabels:
      app: kube-apiserver-vip