apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qbittorrent-external-webui-route
  namespace: qbittorrent
  annotations:
    external-dns.alpha.kubernetes.io/enabled: "true" 
    external-dns.alpha.kubernetes.io/hostname: qbittorrent2.szilardshome.com
    external-dns.alpha.kubernetes.io/ttl: "120"
spec:
  parentRefs:
    - name: traefik-external
      namespace: traefik-external
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: qbittorrent
          port: 8080
          weight: 1