apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  storageClassName: longhorn