apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  type: ClusterIP
  ports:
  - name: webui
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: torrrent
    port: 6882
    protocol: TCP
    targetPort: 6882
  selector:
    app.kubernetes.io/name: qbittorrent