apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  - port: 6881
    protocol: TCP
    targetPort: 6881  
  selector:
    app.kubernetes.io/name: qbittorrent