apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: pv-radarr-data
  namespace: radarr
spec:
  capacity:
    storage: 21.02Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb-k3s
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: radarr
    volumeAttributes:
      source: "//10.10.2.100/media" 
    nodeStageSecretRef:
      name: smbcreds
      namespace: csi-driver-smb