apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-radarr-config
  namespace: radarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "3Gi"
  storageClassName: longhorn