kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-radarr-data
  namespace: radarr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 21Ti
  volumeName: pv-radarr-smb
  storageClassName: smb