apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare-secret
  namespace: external-dns-cloudflare
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    name: cloudflared-api-token
    creationPolicy: Owner
  data:
  - secretKey: apiKey
    remoteRef:
      key: "cloudflared-api-token"
      property: apiKey