apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard-external-route 
  namespace: traefik
spec:
  parentRefs:
    - name: gateway-traefik-external
      namespace: traefik
  hostnames:
    - "traefik-external.szilardshome.com" 
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs: 
        - name: api@internal
          kind: TraefikService
          group: traefik.io 
          port: 8080