apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: v35.4.0
    releaseName: traefik-external
    namespace: traefik
    valuesFile: values.yaml
#    includeCRDs: false
