apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
#  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/experimental-install.yaml
  - gateway-external.yaml
  - gatewayclass.yaml


helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: v35.4.0
    releaseName: traefik-external
    namespace: traefik
    valuesFile: values.yaml
#    includeCRDs: false
