globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"
  - "--experimental.kubernetesgateway"
  - "--providers.kubernetesgateway"
  - "--providers.kubernetesgateway.labelselector=gatewayclass.szilardshome.com/type=traefik-external"                          

# ----- Deployment -----
deployment:
  enabled: true
  kind: Deployment 
  replicas: 3      

# ----- Portok (Traefik Entrypoints) -----
ports:
  traefik:
    port: 8080
  web:
    redirections:
      entrypoint:
        to: "websecure"                    
        scheme: "https"                    
        permanent: true   
  websecure:
    http3:
      enabled: true
    advertisedPort: 4443
    tls:
      enabled: true                      

# ----- IngressRoute (Dashboard disabled) -----
ingressRoute:
  dashboard:
    enabled: false

# ----- Providers -----
providers:
  kubernetesCRD:
    enabled: true                          
  kubernetesIngress:
    enabled: false      
  kubernetesGateway:
    enabled: true

gatewayClass:  # @schema additionalProperties: false
  # -- When providers.kubernetesGateway.enabled and gateway.enabled, deploy a default gatewayClass
  enabled: true
  # -- Set a custom name to GatewayClass
  name: traefik-external
  labels:
    gatewayclass.szilardshome.com/type: traefik-external

gateway:
  enabled: true
  name: "traefik-external"
  listeners:
    web:
      port: 8000
      hostname: "*.szilardshome.com"
      protocol: HTTP
      namespacePolicy: All
    websecure:
      port: 8443
      hostname: "*.szilardshome.com"
      protocol: HTTPS
      namespacePolicy: All
      certificateRefs:
        - name: tls-external-cert
          kind: Secret
      mode: Terminate

# ----- Service -----
service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.10.4.61       