apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-internal-wildcard-cert"
  namespace: "traefik-internal"
spec:
  secretName: "tls-internal-wildcard-cert"
  issuerRef:
    name: "cloudflare-cluster-issuer"
    kind: ClusterIssuer
  commonName: "*.internal.szilardshome.com" 
  dnsNames:
  - "internal.szilardshome.com"
  - "*.internal.szilardshome.com"