---
- name: Update servers and sequentially reboot if necessary
  hosts: k3s_cluster  
  become: true        
  serial: 1                                                  

  tasks:
    - name: Update APT package cache (apt update)
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false 

    - name: Upgrade all packages to the latest version (apt upgrade -y)
      ansible.builtin.apt:
        upgrade: dist   
        autoremove: yes 
      register: apt_upgrade_status

    - name: Check if server reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required 
      register: reboot_required_file
      changed_when: false 

    - name: Log reboot status (optional)
      ansible.builtin.debug:
        msg: "Server {{ inventory_hostname }} requires reboot: {{ reboot_required_file.stat.exists }}"
      when: reboot_required_file.stat.exists

    - name: Reboot server if necessary
      ansible.builtin.reboot:
        msg: "Rebooting server {{ inventory_hostname }} after system updates."
        connect_timeout: 10      
        reboot_timeout: 900      
        pre_reboot_delay: 5      
        post_reboot_delay: 60    
        test_command: "whoami"   
      when: reboot_required_file.stat.exists 