apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
  - namespace.yaml
  - httproute.yaml
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.8.1
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml
    includeCRDs: true