defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
  defaultFsType: ext4
  reclaimPolicy: Retain
ingress:
  enabled: false