apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-internal
  namespace: traefik-internal
spec:
  addresses:
  - type: IPAddress
    value: 10.10.4.70
  gatewayClassName: traefik-internal-gateway-class
  listeners:
    - name: http
      protocol: HTTP
      port: 8000
      hostname: "*.szilardshome.com"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 8443
      hostname: "*.szilardshome.com"
      tls:
        certificateRefs:
          - name: tls-internal-cert
            kind: Secret
            namespace: cert-manager
            group: "" # required
      allowedRoutes:
        namespaces:
          from: All