apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: traefik-dashboard-internal-route 
  namespace: traefik-internal
spec:
  parentRefs:
    - name: traefik-internal-gateway
      namespace: traefik-internal
  hostnames:
    - "traefik-internal.szilardshome.com" 
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs: 
        - name: api@internal
          kind: TraefikService
          group: traefik.io 
          port: 8080