globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    redirections:
      entrypoint:
        to: websecure
        priority: 10
  websecure:
    http3:
      enabled: true
    advertisedPort: 4443
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false
    
providers:
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true 
  name: "gateway-traefik-internal"
  listeners: # Objektum (map), nem lista!
    web: # A listener neve a kulcs
      protocol: HTTP
      port: 8000
      hostname: "*.szilardshome.com"
      allowedRoutes:
        namespaces:
          from: All
    websecure:
      protocol: HTTPS
      port: 8443
      hostname: "*.szilardshome.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: tls-internal-cert
gatewayClass: 
  enabled: true
  name: "traefik-internal-class"

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 10.10.4.70 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []