globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"                        

# ----- Deployment -----
deployment:
  enabled: true
  kind: Deployment 
  replicas: 3      

# ----- Portok (Traefik Entrypoints) -----
ports:
  web:
    redirections:
      entrypoint:
        to: websecure
        priority: 10
  websecure:
    http3:
      enabled: true
    advertisedPort: 4443
    tls:
      enabled: true                      

# ----- IngressRoute (Dashboard disabled) -----
ingressRoute:
  dashboard:
    enabled: false

# ----- Providers -----
providers:
  kubernetesCRD:
    enabled: true                          
  kubernetesIngress:
    enabled: false                         

# ----- Service -----
service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.10.4.60         