globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
  - "--providers.kubernetesGateway.experimentalChannel=true"
  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=DEBUG"                        

# ----- Deployment -----
deployment:
  enabled: true
  kind: Deployment 
  replicas: 3      

# ----- Portok (Traefik Entrypoints) -----
ports:
  web:
    port: 8000                             
    exposedPort: 80                        
    redirections:
      entryPoint:
        to: "websecure"                    
        scheme: "https"                    
        permanent: true                    
  websecure:
    port: 8443                            
    exposedPort: 4443                      
    advertisedPort: 4443                   
    tls:
      enabled: true                       
    http3:
      enabled: true                        

# ----- IngressRoute (Dashboard disabled) -----
ingressRoute:
  dashboard:
    enabled: false

# ----- Providers -----
providers:
  kubernetesCRD:
    enabled: true                          
  kubernetesIngress:
    enabled: false                         
  kubernetesGateway:
    enabled: true        
    experimentalChannel: true             

# ----- Gateway -----
gateway:
  enabled: true
  name: "gateway-traefik-internal"        
  listeners:
    web: 
      port: 8000                           
      protocol: HTTP                       
      hostname: "*.szilardshome.com"       
      allowedRoutes:
        namespaces:
          from: "All"
    websecure:
      port: 8443                          
      protocol: HTTPS                      
      hostname: "*.szilardshome.com"       
      mode: Terminate       
      namespacePolicy: All              
      certificateRefs:                    
        - name: tls-internal-cert          
          kind: Secret                     
          namespace: cert-manager
# ----- GatewayClass  -----
gatewayClass:
  enabled: true
  name: "traefik-internal-class" 

rbac:
  enabled: true
experimental:
  kubernetesGateway:
    # -- Enable traefik experimental GatewayClass CRD
    enabled: true
# ----- Service -----
service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: 10.10.4.70             