provider: cloudflare
cloudflare:
  apiToken: CF_API_TOKEN
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflared-api-token
        key: apiKey

policy: sync
sources: ["ingress", "service", "gateway-httproute"]
txtOwnerId: default
txtPrefix: k3s.
domainFilters: ["szilardshome.com"]
extraArgs:
  - --cloudflare-proxied
  - --cloudflare-dns-records-per-page=5000
  # - --default-targets=${YOUR_HOUSE_EXTERNAL_IP}