apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "10.10.4.64/27"  # 10.10.4.65-10.10.4.94
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs 
