apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-vip
  namespace: kube-system
  labels:
    app: kube-apiserver-vip
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.4.199
  ports:
    - name: https
      port: 6443
      protocol: TCP
      targetPort: 6443
  sessionAffinity: None